INSERT INTO MUSIC (DURATION, MUSICAL_STYLE, NAME, NAME_ARTIST, RELEASE_DATE) VALUES ('05m', 'Pop', 'Love', 'Taylor', '12/05')
INSERT INTO MUSIC (DURATION, MUSICAL_STYLE, NAME, NAME_ARTIST, RELEASE_DATE) VALUES ('03m', 'Pop', 'My', 'Miles', '24/08')
INSERT INTO MUSIC (DURATION, MUSICAL_STYLE, NAME, NAME_ARTIST, RELEASE_DATE) VALUES ('02m', 'Pop', 'Friend', 'Jay Z', '08/06')
